substitutions:
  name: "dual-smart-plug"
  friendly_name: Dual Smart Plug
  comment: "bk7231n Smart Plug 20A 117"
  board: cb2s
  voltage_divider: "786.4"
  current_resistor: "0.00106"
  current_multiply: "0.4558"


esphome:
  name: ${name} 
  friendly_name: ${friendly_name}
  comment: ${comment}
  project:
    name: "Tuya.Dual-Smart-Plug-20A"
    version: "Wifi.ESPhome-Craft"
  on_boot:
    priority: 600
    then:       
      - lock.unlock: child_lock            
  
bk72xx:
  board: ${board} 
  framework:
    version: latest

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret hotspot_pw

wifi:
  id: iptime
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  fast_connect: True
  reboot_timeout: 0s

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ${friendly_name} hotspot
    password: !secret hotspot_pw

captive_portal:

time:
  - platform: sntp
    id: time_comp
    timezone: Asia/Seoul

binary_sensor:
  - platform: status
    name: "API Connection"
    id: c_status

  - platform: template
    id: warning
    name: 'Overload Warning'
    device_class: problem

  - platform: gpio
    device_class: power
    internal: True
    pin:
      number: 11
      mode: INPUT_PULLUP
      inverted: True
    name: Button # Name to make button visible in HA
    on_click:      
      - min_length: 50ms
        max_length: 1000ms
        then:          
          - if: 
              condition:
                and:
                  - lock.is_unlocked: child_lock
                  - binary_sensor.is_off: warning                      
              then: 
               - switch.toggle: relay_1
              else:
                - repeat:
                    count: 2
                    then:
                      - light.turn_on: wifi_led
                      - delay: 0.5s
                      - light.turn_off: wifi_led
                      - delay: 0.5s
                      

    on_multi_click:
      - timing:
        - ON for at least 5s   
        - OFF for at least 0.5s     
        then:
          - if: # if lock is lock, do unlock
              condition:
                lock.is_locked: child_lock
              then:
                  - lock.unlock: child_lock
                  - logger.log: "unlock"
                  - light.turn_on: wifi_led
                  - delay: 1.5s                   

              else: # if lock is unlock, do lock
                  - lock.lock: child_lock
                  - logger.log: "locked"
                  - repeat:
                      count: 2
                      then:
                        - light.turn_on: wifi_led
                        - delay: 0.5s
                        - light.turn_off: wifi_led
                        - delay: 0.5s 
      - timing:
        - ON for at least 10s   
        - OFF for at least 0.5s
        then:
          - button.press: re_start
  - platform: gpio
    device_class: power
    internal: True
    pin:
      number: 26
      mode: INPUT_PULLUP
      inverted: True
    name: Button # Name to make button visible in HA
    on_click:      
      - min_length: 50ms
        max_length: 1000ms
        then:          
          - if: 
              condition:
                and:
                  - lock.is_unlocked: child_lock
                  - binary_sensor.is_off: warning                      
              then: 
               - switch.toggle: relay_2
              else:
                - repeat:
                    count: 2
                    then:
                      - light.turn_on: wifi_led
                      - delay: 0.5s
                      - light.turn_off: wifi_led
                      - delay: 0.5s                     

    on_multi_click:
      - timing:
        - ON for at least 5s   
        - OFF for at least 0.5s     
        then:
          - if: # if lock is lock, do unlock
              condition:
                lock.is_locked: child_lock
              then:
                  - lock.unlock: child_lock
                  - logger.log: "unlock"
                  - light.turn_on: wifi_led
                  - delay: 1.5s       

              else: # if lock is unlock, do lock
                  - lock.lock: child_lock
                  - logger.log: "locked"
                  - repeat:
                      count: 2
                      then:
                        - light.turn_on: wifi_led
                        - delay: 0.5s
                        - light.turn_off: wifi_led
                        - delay: 0.5s 
      - timing:
        - ON for at least 10s   
        - OFF for at least 0.5s
        then:
          - button.press: re_start

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    internal: true
    update_interval: 300s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

  - platform: internal_temperature
    name: "Internal Temperature"
    id: in_temp
    on_value:
      then:
        - if:
            condition:
              and:
                - switch.is_on: switch_olp
                - for:
                    time: 300s
                    condition:
                      - lambda: return (id(in_temp).state > 65);
            then:
              - logger.log: "Overload Temp"
              - lambda: id(warning).publish_state(true);
              - switch.turn_off: relay_1
              - switch.turn_off: relay_2

  - platform: total_daily_energy
    name: 'Total Daily Energy'
    id: solar_daily
    power_id: power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    icon: mdi:counter
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  - platform: hlw8012
    model: BL0937
    change_mode_every: 6
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    sel_pin:
      number: 23
      inverted: true
    cf_pin: 
      number: 6
      inverted: true
      mode: input_pullup
    cf1_pin: 
      number: 7
      inverted: true
      mode: input_pullup
    current:
      name: "Current"
      id: current
      icon: mdi:current-ac
      #internal: true
      filters:        
        - multiply: ${current_multiply}
        - delta: 0.1
      unit_of_measurement: A
      disabled_by_default: true
      on_value:
        - if:
            condition:
              for:
                time: 2s
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(current).state >= 20 * 1.2);
            then:
              - logger.log: "Overload 20A"
              - lambda: id(warning).publish_state(true);
              - switch.turn_off: relay_1
              - switch.turn_off: relay_2
        - if:
            condition:
              for:
                time: 2min
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(current).state >= 18);
            then:
              - logger.log: "Overload 18A"
              - switch.turn_off: relay_1
              - switch.turn_off: relay_2
              - lambda: id(warning).publish_state(true);
        - if:
            condition:
              for:
                time: 60min
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(current).state >= 16 );
            then:
              - logger.log: "Overload 16A"
              - switch.turn_off: relay_1
              - switch.turn_off: relay_2
              - lambda: id(warning).publish_state(true);
        - script.execute: power_save
    voltage:
      name: "Voltage"
      id: voltage
      #internal: true
      disabled_by_default: true
      accuracy_decimals: 1
      filters:
        - delta: 2
        - sliding_window_moving_average: 
            window_size: 6 
            send_every: 1 
            send_first_at: 1

    power:
      name: "Power"
      id: power
      #internal: true
      accuracy_decimals: 1 
      filters:
        - delta: 0.5
      on_value:
        then:
          if:
            condition:
              lambda: return x <= id(set_num).state;
            then:
              - script.execute: power_save
    update_interval: 1s

number:
  - platform: template
    name: "Stanby Cutoff"
    id: set_num
    optimistic: true
    icon: mdi:numeric
    min_value: 0
    max_value: 100
    initial_value: 5
    unit_of_measurement: W
    step: 5
    restore_value: True
    entity_category: config
    on_value: 
      then:
        - script.execute: power_save

text_sensor:
  - platform: version
    name: "Esphome Version"
  - platform: wifi_info
    ip_address:
     name: Device IP Address

light:
  - platform: status_led
    name: "Wifi LED"
    id: wifi_led
    pin: 
      number: 10
      inverted: false 
    internal: true

button:    
  - platform: restart
    name: "Restart"
    id: re_start
    entity_category: diagnostic
  - platform: template
    name: "Overload Reset"
    on_press: 
      then:
        - lambda: id(warning).publish_state(false);
        
    
switch:
  # Relay itself
  - platform: gpio
    name: "Socket 1"
    pin: GPIO24
    id: relay_1
    icon: mdi:power-socket-de
    device_class: outlet
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Socket 2"
    pin: GPIO8
    id: relay_2
    icon: mdi:power-socket-de
    device_class: outlet
    restore_mode: RESTORE_DEFAULT_OFF 

  # Overload Protect
  - platform: template
    name: "OverLoad Protection"    
    id: switch_olp
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:toggle-switch
    optimistic: true
    entity_category: config
  # Stanby Power Save
  - platform: template
    name: "Energy Saving Mode"    
    id: switch_save
    icon: mdi:toggle-switch
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: config
    turn_on_action:
      - script.execute: power_save
    turn_off_action: 
      - script.stop: power_save   
  - platform: template
    name: "All Socket"
    id: all_socket
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:toggle-switch
    optimistic: true
    lambda: return (id(relay_1).state || id(relay_2).state);
    turn_on_action: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
    turn_off_action: 
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2
# Relay itself
lock:  
  - platform: template
    name:  "Child's Lock"
    id: child_lock
    optimistic: true
    entity_category: config

script:
  - id: power_save
    then:
      - if:
          condition:
           and:
             - or:
                 - switch.is_on: relay_1
                 - switch.is_on: relay_2
             - switch.is_on: switch_save
             - for:
                 time: 300s
                 condition:
                   - lambda: return (id(power).state <= id(set_num).state );
          then: 
            - switch.turn_off: all_socket
